### ISSUE TITLE
Allow null items to be inserted in stacks and queues?

### ISSUE THREAD

**Issue by avinash-rath** [DSAlgoTeam/Algorithms#5]
https://github.com/DSAlgoTeam/Algorithms/blob/33062397dbcd8dfdfc4a6865d56995b7d5c99160/Python/Algorithms/data_structures/linked_list.py#L37

Should we allow `null` to be inserted into the FIFO and LIFO lists? There may be specific cases where one may want to insert a null value into the queue or a stack.

**Comment by sribs** [comment]
python do not have the concept of ```null```. Instead it uses ```None```. Not sure if I understand you correctly

**Comment by avinash-rath** [comment]
> python do not have the concept of `null`. Instead it uses `None`. Not sure if I understand you correctly

I meant `None`. Looking at a specific case where I might want to insert `None` into the list, which might look like this,
```
1 -> 2 -> 'abc' -> None -> 3
```
I think we should support that too

**Comment by sribs** [comment]
No. This creates lot of chaos and null deref bug
